node:
  cluster: example
  id: node-1
dynamic_resources:
  cds_config:
    path: /tmp/cds.yaml
  lds_config:
    path: /tmp/lds.yaml
admin:
  access_log_path: /dev/null
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 19000
