name: prototype CI to Docker Hub
on:
  push:
    branches: [ main ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: "Build:buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build:login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: ./cmd/prototype
          file: ./cmd/prototype/Dockerfile
          push: true
          tags: ghcr.io/dgzlopes/prototype:latest